### ISSUE TITLE
?? missing characters

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#13]
As @Andhrabharati mentioned, there are several cases in ap90.txt where '??' is used to indicate missing text.

This issue devoted to finding unicode or devanagari to fix these omissions.

**Comment by funderburkjim** [comment]
## meter
These are in the 'Prosody' appendix.

The symbols used in mw.txt for long and short syllables are (ref: [mw-meta2](https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/mw/mw-meta2.txt)) :
```
¯  (\u00af)    53 := MACRON  Long in metric pattern
˘  (\u02d8)    48 := BREVE   Short in metric pattern
```
[Page 1179](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1179) changes:
![image](https://user-images.githubusercontent.com/6393033/117210600-e362d600-adc5-11eb-9ce0-c93ad00d5724.png)

```
; Prosody. p. 1179
265324 old <HI>Expressed in symbols (the symbol {??} denoting a
265324 new <HI>Expressed in symbols (the symbol ˘ denoting a
; also change '--' to the long meter symbol
265325 old <>short syllable, and --a long one), the different
265325 new <>short syllable, and ¯ a long one), the different
265327 old <>{#ya#} {??} (Bacchius)
265327 new <>{#ya#} ˘ ¯ ¯ (Bacchius)
265328 old <>{#ra#} {??} (Amphimacer)
265328 new <>{#ra#} ¯ ˘ ¯ (Amphimacer)
265329 old <>{#ta#} {??} (Anti-bacchius)
265329 new <>{#ta#} ¯ ¯ ˘ (Anti-bacchius)
265330 old <>{#Ba#} {??} (Dactylus)
265330 new <>{#Ba#} ¯ ˘ ˘ (Dactylus)
265331 old <>{#ja#} {??} (Amphibrachys)
265331 new <>{#ja#} ˘ ¯ ˘ (Amphibrachys)
265332 old <>{#sa#} {??} (Anapæstus)
265332 new <>{#sa#} ˘ ˘ ¯ (Anapæstus)
265333 old <>{#ma#} {??} (Molossus)
265333 new <>{#ma#} ¯ ¯ ¯ (Molossus)
265334 old <>{#na#} {??} (Tribrachys) 
265334 new <>{#na#} ˘ ˘ ˘ (Tribrachys)
```

[Page 1180](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1180)
![image](https://user-images.githubusercontent.com/6393033/117210741-173dfb80-adc6-11eb-8923-b8a1ba225f52.png)
Changes:
```
; p. 1180
265336 old <>Similarly {#la#} ({??}) is used to denote a short syllable,
265336 new <>Similarly {#la#} (˘) is used to denote a short syllable,
265337 old <>and {#ga#} (--) a long one.
265337 new <>and {#ga#} (¯) a long one.
```
[Page 1189](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1189)
![image](https://user-images.githubusercontent.com/6393033/117210897-4d7b7b00-adc6-11eb-9baf-06dd34658bed.png)

Changes:
```
; page 1189
266279 old <>followed by a {#ragaRa#} (-{??}-) and a short and a long vowel,
266279 new <>followed by a {#ragaRa#} ( ¯ ˘ ¯ ) and a short and a long vowel,
266280 old <>({??}-). The rules further require that the syllabic <lbinfo n="in+stants"/>
266280 new <>( ˘ ¯ ). The rules further require that the syllabic <lbinfo n="in+stants"/>
````

**Comment by funderburkjim** [comment]
## semicircle:
[Page 614](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=614)

नादः [Printed book page 0613-c]
![image](https://user-images.githubusercontent.com/6393033/117211896-97189580-adc7-11eb-885c-378facbb5c83.png)

नादः [नद्-घञ्] 1 A loud roar, ery, shout, sounding, roaring; सिंहनादः, घनº &c.
— 2 A sound in general; Māl. 5. 20. 
— 3 (In Yoga phil.) The nasal sound represented by a
[Page0614-a+ 54]
semi-circle ({??}).

No idea how to represent this

**Comment by funderburkjim** [comment]
## under viDi  - Devanagari
[Page 977](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=0977).
![image](https://user-images.githubusercontent.com/6393033/117212790-c8459580-adc8-11eb-8bed-1bf6888ab49b.png)

```
219656 old <>Creation, formation; {#sAma{??}yaviDO#}
219656 new <>Creation, formation; {#sAmagryaviDO#}
```

**Comment by funderburkjim** [comment]
## Devanagari - Help wanted
[Page 1183](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1183)
![image](https://user-images.githubusercontent.com/6393033/117213936-422a4e80-adca-11eb-8356-7daa66ba96e2.png)

Help Wanted:
```
265685 old <>{#DanAnyar{??}yaDvaM DanAnyarjayaDvam ..#}
265685 new <>{#DanAnyar{??}yaDvaM DanAnyarjayaDvam ..#}
265691 old <>{#goviMdapadAbje rAjI naKa{??}#} <lbinfo n="RA#mAstAM"/>
265691 new <>{#goviMdapadAbje rAjI naKa{??}#} <lbinfo n="RA#mAstAM"/>
```

**Comment by funderburkjim** [comment]
## Devanagari, help wanted
[Page 1183-b](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1183)
![image](https://user-images.githubusercontent.com/6393033/117214455-d8f70b00-adca-11eb-8c6f-15c7bc9a6361.png)

Changes (Help wanted):
```
265733 old <>{#vrajakAminIka{??}linIkftakeliH .#}
265733 new <>{#vrajakAminIka{??}linIkftakeliH .#}
```

**Comment by funderburkjim** [comment]
## Devanagari - 
[Page 1187](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1187)
![image](https://user-images.githubusercontent.com/6393033/117215057-b31e3600-adcb-11eb-822a-37d7eb1c1538.png)


Changes (Please check):  (ti)
```
266087 old <>{#kzitivalaye'sti kaMsaSamanastave{??} tamavocadadritanayA ..#}
266087 new <>{#kzitivalaye'sti kaMsaSamanastaveti tamavocadadritanayA ..#}
```

**Comment by Andhrabharati** [comment]
> ## semicircle:
> 
> [Page 614](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=614)
> 
> नादः [Printed book page 0613-c]
> ![image](https://user-images.githubusercontent.com/6393033/117211896-97189580-adc7-11eb-885c-378facbb5c83.png)
> 
> नादः [नद्-घञ्] 1 A loud roar, ery, shout, sounding, roaring; सिंहनादः, घनº &c.
> — 2 A sound in general; Māl. 5. 20.
> — 3 (In Yoga phil.) The nasal sound represented by a
> [Page0614-a+ 54]
> semi-circle ({??}).
> 
> No idea how to represent this

Simple, this is the chandrabindu character in Devanagari!!

**Comment by Andhrabharati** [comment]
> ## Devanagari - Help wanted
> 
> [Page 1183](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1183)
> ![image](https://user-images.githubusercontent.com/6393033/117213936-422a4e80-adca-11eb-8356-7daa66ba96e2.png)
> 
> Help Wanted:
> 
> ```
> 265685 old <>{#DanAnyar{??}yaDvaM DanAnyarjayaDvam ..#}
> 265685 new <>{#DanAnyar{??}yaDvaM DanAnyarjayaDvam ..#}
> 265691 old <>{#goviMdapadAbje rAjI naKa{??}#} <lbinfo n="RA#mAstAM"/>
> 265691 new <>{#goviMdapadAbje rAjI naKa{??}#} <lbinfo n="RA#mAstAM"/>
> ```

(10) rNa

(11) rA

**Comment by Andhrabharati** [comment]
> ## Devanagari, help wanted
> 
> [Page 1183-b](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1183)
> ![image](https://user-images.githubusercontent.com/6393033/117214455-d8f70b00-adca-11eb-8c6f-15c7bc9a6361.png)
> 
> Changes (Help wanted):
> 
> ```
> 265733 old <>{#vrajakAminIka{??}linIkftakeliH .#}
> 265733 new <>{#vrajakAminIka{??}linIkftakeliH .#}
> ```

(1) pa

**Comment by Andhrabharati** [comment]
> ## Devanagari -
> 
> [Page 1187](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ap90&page=1187)
> ![image](https://user-images.githubusercontent.com/6393033/117215057-b31e3600-adcb-11eb-822a-37d7eb1c1538.png)
> 
> Changes (Please check): (ti)
> 
> ```
> 266087 old <>{#kzitivalaye'sti kaMsaSamanastave{??} tamavocadadritanayA ..#}
> 266087 new <>{#kzitivalaye'sti kaMsaSamanastaveti tamavocadadritanayA ..#}
> ```

Yes, it is 'ti'.

**Comment by funderburkjim** [comment]
> rNa

Which nasal is that?  ङ  (slp1 N) or ण (slp1 R) ?

**Comment by funderburkjim** [comment]
> 265733 new <>{#vrajakAminIka{??}linIkftakeliH .#}

I think this is 'ma':  <>{#vrajakAminIkamalinIkftakeliH .#}

Based on Printed ap57, Appendix A, p. 7 (Meters with 13 syllables in a quarter)

**Comment by gasyoun** [comment]
> semi-circle ({??}).

◡ or ⩊ or ◛  

https://unicode-search.net/unicode-namesearch.pl?term=CIRCLE

![ffdsdfdf](https://user-images.githubusercontent.com/80761/117301932-ca205f00-ae83-11eb-95aa-132049fa7bf1.png)

**Comment by funderburkjim** [comment]
Semi-circle or bindu?

1. The image in the AP90 page  (see [above](https://github.com/sanskrit-lexicon/AP90/issues/13#issuecomment-833109034)) does look like a candra-bindu (there is a dot above the semicircle).
2. Interestingly, in the printed AP57 There is NO image.
   ![image](https://user-images.githubusercontent.com/6393033/117497309-56935600-af46-11eb-8d1e-debde1b26dfc.png)
3. I could find no visual image of this 'semicircle' in nAda yoga web searches.  It would be nice to find some Sanskrit Document on this topic where the symbol in question is either shown visually or described in some unambiguous way.

Conclusion:  I'll use the U+25E1 character (lower half circle) for now at least;

**Comment by funderburkjim** [comment]
@Andhrabharati  and @gasyoun   --- thanks for feedback on these questions.

**Comment by funderburkjim** [comment]
Changes installed in csl-orig repository at [this commit](https://github.com/sanskrit-lexicon/csl-orig/commit/ba10fd4eb66f41bf9a525122319406cb9fb5390d).

For reference, here is the change file used by updateBiLine.py:
[temp_correction_qq.txt](https://github.com/sanskrit-lexicon/AP90/files/6443920/temp_correction_qq.txt)

**Comment by Andhrabharati** [comment]
> 
> 
> Semi-circle or bindu?
> 
>     1. The image in the AP90 page  (see [above](https://github.com/sanskrit-lexicon/AP90/issues/13#issuecomment-833109034)) does look like a candra-bindu (there is a dot above the semicircle).
> 
>     2. Interestingly, in the printed AP57 There is NO image.
>        ![image](https://user-images.githubusercontent.com/6393033/117497309-56935600-af46-11eb-8d1e-debde1b26dfc.png)
> 
>     3. I could find no visual image of this 'semicircle' in nAda yoga web searches.  It would be nice to find some Sanskrit Document on this topic where the symbol in question is either shown visually or described in some unambiguous way.
> 
> 

pl. see this link-
https://books.google.co.in/books?id=ZgybmMnWpaUC&pg=PA81&lpg=PA81&dq=nasal+sound+represented+by+semicircle&source=bl&ots=xF3DwtUc81&sig=ACfU3U2ayR8RIeT4ib0eA_NimScRnVW9eA&hl=te&sa=X&ved=2ahUKEwjjxpbksLjwAhUf_XMBHWbYANMQ6AEwEnoECAUQAw

(The last line in p.81 continuing to p.82 shows/discusses this clearly.)

**Comment by gasyoun** [comment]
> Conclusion: I'll use the U+25E1 character (lower half circle) for now at least;

That should be enough for now.

> [Interestingly this is referring to the same Apte entry!!]

Good catch, as usual.

**Comment by funderburkjim** [comment]
Interesting discussion of p.81/2.   
![image](https://user-images.githubusercontent.com/6393033/117505486-1934c580-af52-11eb-977f-8282bfe83d4d.png)

![image](https://user-images.githubusercontent.com/6393033/117505570-3ec1cf00-af52-11eb-937c-9b72c7be800b.png)

Another possibility for the 'semicircle' might be U+1CD8 (VEDIC TONE CANDRA BELOW) shown in
[Unicode Vedic Extensions](https://en.wikipedia.org/wiki/Vedic_Extensions)
