### ISSUE TITLE
ap90ab -- missing hyphens in  derivations

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#18]
A small problem was encountered when doing a transcoding of ap90ab.txt.

I first transcoded from the (native) Devanagari to slp1,  and then, transcoded back from slp1 to Devanagari.  Then I did 
a diff between the original and the derived Devanagari version.  The two should be identical (no differences), but there 
are differences in 20 lines:

```
3652c3652
< 01218 (0025,c) <p> अज्जु(ज्जू)का [अर्जयति या सा, अर्ज्ऊक, पृ. रकारस्य जत्वम् <Tv.>]
---
> 01218 (0025,c) <p> अज्जु(ज्जू)का [अर्जयति या सा, अर्जूक, पृ. रकारस्य जत्वम् <Tv.>]
3871c3871
< 01291 (0027,b) <p> अंजिष्ठः, −ष्णुः [अनक्ति स्वकिरणैः विश्वं; अंज्इष्ठच्-इष्णुच् <Uṇ.> 4. 2]
---
> 01291 (0027,b) <p> अंजिष्ठः, −ष्णुः [अनक्ति स्वकिरणैः विश्वं; अंजिष्ठच्-इष्णुच् <Uṇ.> 4. 2]
4237c4237
< 01413 (0029,b) <p> अतसः [अतति गच्छति इत्यतसः अत्असच् <Uṇ.> 3. 117]
---
> 01413 (0029,b) <p> अतसः [अतति गच्छति इत्यतसः अतसच् <Uṇ.> 3. 117]
6769c6769
< 02257 (0049,b) <p> अधियोधः [आधिक्येन युध्यते; युध्अच्]
---
> 02257 (0049,b) <p> अधियोधः [आधिक्येन युध्यते; युधच्]
9226c9226
< 03076 (0066,a) <p> अनीकः, −कं [अनिति जीवत्यनेन; अन्ईकन् <Uṇ.> 4. 16-17]
---
> 03076 (0066,a) <p> अनीकः, −कं [अनिति जीवत्यनेन; अनीकन् <Uṇ.> 4. 16-17]
9356c9356
< 	 1. [कामस्य सदृशः अनुरूपो वा] Agreeable to desire, according to one's desire. −2. [अनुकामयते कम्अच्] Desirous, lustful.
---
> 	 1. [कामस्य सदृशः अनुरूपो वा] Agreeable to desire, according to one's desire. −2. [अनुकामयते कमच्] Desirous, lustful.
20461c20461
< 06821 (0151,a) <p> अमावास्य, −स्यक {a.} [अमावास्या, वुन्अष् <P.> IV. 3. 30-31; अमावास्यायां जातः]
---
> 06821 (0151,a) <p> अमावास्य, −स्यक {a.} [अमावास्या, वुनष् <P.> IV. 3. 30-31; अमावास्यायां जातः]
24577c24577
< 08193 (0173,b) <p> अलस {a.} [न लसति व्याप्रियते, लस्अच्]
---
> 08193 (0173,b) <p> अलस {a.} [न लसति व्याप्रियते, लसच्]
32374c32374
< 10792 (0217,c) <+> −जरः [अहोभिः परिवर्तमानो लोकान् जरयति जॄ-णिच्अच्, अहानि वा अस्मिन् जीर्यंति आधारे अप्वा <Tv.>]
---
> 10792 (0217,c) <+> −जरः [अहोभिः परिवर्तमानो लोकान् जरयति जॄ-णिचच्, अहानि वा अस्मिन् जीर्यंति आधारे अप्वा <Tv.>]
37405c37405
< 12469 (0250,b) <p> आम्रातः [आम्रं आम्ररसं अतति अत्अच् <Tv.>]
---
> 12469 (0250,b) <p> आम्रातः [आम्रं आम्ररसं अतति अतच् <Tv.>]
54844c54844
< 18282 (0363,b) <p> औपयज {a.} (जी {f.}) [उपयज्अण्]
---
> 18282 (0363,b) <p> औपयज {a.} (जी {f.}) [उपयजण्]
157153c157153
< 52385 (0885,b) <p> −तिः [यतते मोक्षाय यत्इन्]
---
> 52385 (0885,b) <p> −तिः [यतते मोक्षाय यतिन्]
162454c162454
< 54152 (0914,a) <p> रुच् 1 {A.} (रोचते, रुरुवे, अरुचत्अरोचिष्ट, रोचिष्यते, रुचित)
---
> 54152 (0914,a) <p> रुच् 1 {A.} (रोचते, रुरुवे, अरुचतरोचिष्ट, रोचिष्यते, रुचित)
169615c169615
< 56539 (0950,c) <p> वलभिः, −भी {f.} [वल्यते आच्छाद्यते वल्अभि वा ङीप्] (Also frequently written बडभिः, -भी)
---
> 56539 (0950,c) <p> वलभिः, −भी {f.} [वल्यते आच्छाद्यते वलभि वा ङीप्] (Also frequently written बडभिः, -भी)
189355c189355
< 63119 (1064A,a) <p> श्वेत {a.} (श्वेता or श्वेनी {f.}) [श्वित्अच् घञ् वा]
---
> 63119 (1064A,a) <p> श्वेत {a.} (श्वेता or श्वेनी {f.}) [श्वितच् घञ् वा]
196510c196510
< 65504 (1110,a) <p> सलिलं [सलति गच्छति निम्नं सल्इलच् <Uṇ.> 1. 54]
---
> 65504 (1110,a) <p> सलिलं [सलति गच्छति निम्नं सलिलच् <Uṇ.> 1. 54]
204190c204190
< 68064 (1147,c) <p> स्था 1 {P.} ({Atm.} also in certain senses; तिष्ठति-ते, तस्थौ-तस्थे, अस्यात्अस्थित, स्थास्यति-ते, स्थातुं, स्थित; {pass.} स्थीयते) [the स् of this root is changed to ष् after a preposition ending in इ or उ]
---
> 68064 (1147,c) <p> स्था 1 {P.} ({Atm.} also in certain senses; तिष्ठति-ते, तस्थौ-तस्थे, अस्यातस्थित, स्थास्यति-ते, स्थातुं, स्थित; {pass.} स्थीयते) [the स् of this root is changed to ष् after a preposition ending in इ or उ]
205066c205066
< 68356 (1153,a) <p> स्पृश् 6 {P.} (स्पृशति, पस्पर्श, अस्पृक्षत्अस्पार्क्षीत्-अस्प्राक्षीत्, स्प्रक्ष्यति-स्पर्क्ष्यति, स्पर्ष्टुंस्प्रष्टुं, स्पृष्ट)
---
> 68356 (1153,a) <p> स्पृश् 6 {P.} (स्पृशति, पस्पर्श, अस्पृक्षतस्पार्क्षीत्-अस्प्राक्षीत्, स्प्रक्ष्यति-स्पर्क्ष्यति, स्पर्ष्टुंस्प्रष्टुं, स्पृष्ट)
205675c205675
< 68559 (1156,c) <p> स्यंद् 1 {A.} (स्यंदते, सस्यंदे, अस्यदत्अस्यंत्त-अस्यंदिष्ट, स्यंत्स्यति-ते, स्यंदिष्यते, स्यंदितुं-स्यंत्तुं, स्यन्न; {desid.} सिस्यंदिषते, सिस्यंत्सति-ते; the स् of स्यंद् is changed to ष् after a preposition ending in इ or उ)
---
> 68559 (1156,c) <p> स्यंद् 1 {A.} (स्यंदते, सस्यंदे, अस्यदतस्यंत्त-अस्यंदिष्ट, स्यंत्स्यति-ते, स्यंदिष्यते, स्यंदितुं-स्यंत्तुं, स्यन्न; {desid.} सिस्यंदिषते, सिस्यंत्सति-ते; the स् of स्यंद् is changed to ष् after a preposition ending in इ or उ)
206761c206761
< 68921 (1162,a) <p> स्वातिः, −ती {f.} [स्वेनैव अतति अत्इन् स्त्रीत्वपक्षे वा ङीप्]
---
> 68921 (1162,a) <p> स्वातिः, −ती {f.} [स्वेनैव अतति अतिन् स्त्रीत्वपक्षे वा ङीप्]
```

The first difference (under headword ajjukA) is 'अर्ज्ऊक'  in ap90ab, vs. `अर्जूक` in the derived.  The others are similar.
These are in the bracketed derivation sections, and the text has a hyphen  अर्ज्-ऊक .  The cases I've examined all have
a hyphen at the point of difference.

@Andhrabharati   Request that you insert the '-' in ap90ab.txt in these cases and push the change to github.

**Comment by Andhrabharati** [comment]
The derived text matter in the front  portion of my file was done in some different manner than others (regular way). So some error has crept-in there.

A good finding indeed.

I have a check for halant-after-halant which is hard to notice and prone to skipping the eyes; now to add this additional check also- vowel-after-halant in my process.

Will correct these and also the other ones I mentioned as "to be done" in my file.

BTW, today I am going to start the HWs portion (probably will include all the front matter) proofing.

**Comment by Andhrabharati** [comment]
These 20 reported are the only cases for vowel-after halant.

Also corrected many meaning numbers that are not in sequence (@funderburkjim seems to have corrected all such in his text), and split 3 more L-entries (20992A, 27472A and 46407A).

**The modified ap90ab.txt file is uploaded to the repo.**

**Comment by Andhrabharati** [comment]
> I first transcoded from the (native) Devanagari to slp1, and then, transcoded back from slp1 to Devanagari.

But why did the first conversion of "Devanagari to slp1" ignored the halant present here?

**Comment by funderburkjim** [comment]
@Andhrabharati 

* Pushed your new ap90ab to github
  * you should now 'pull' ap90 repository so your local version is in sync with github
* confirmed that the 20 lines now cause no problem in the transcoding
  * `why did the first conversion of "Devanagari to slp1" ignore the halant present here?`   Not sure, but it was helpful to identify those 20 lines.
* added 'corrections' team, with write privileges, to ap90 repository.  Since @Andhrabharati is in the corrections team,
  you should be able to push changes to ap90 from now on -- similar to way you can push changes to mws repository.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Hope you're looking at my posts at the other threads (#15, #16 and #17)  also.

**Comment by gasyoun** [comment]
> added 'corrections' team, with write privileges, to ap90 repository. Since @Andhrabharati is in the corrections team

Thanks.
