### ISSUE TITLE
nyAya maxims, appendix writers/places

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#20]
In current ap90.txt, there are 30 entries for nyAya maxims:  L=17490-17519
  First one: L=17490 aMDacawakanyAyaH
 https://sanskrit-lexicon.uni-koeln.de/simple/ap90/aMDacawakanyAyaH/slp1

The nyAya maxims should probably be removed from ap90.txt entries and
handled in some other way  (e.g.  aMDacawakanyAyaH, etc. removed as headwords.)
They are in an appendix in ap57.

L-numbers 32000-32030  are from Appendix II (Important Sanskrit writers)
  e.g. https://sanskrit-lexicon.uni-koeln.de/simple/ap90/aMga/slp1

L-numbers 32100-32175 are from Appendix III (important geographical names)

**Comment by Andhrabharati** [comment]
You may consider relocating them as in

[न्यायः.txt](https://github.com/sanskrit-lexicon/AP90/files/6564986/default.txt)

if they are removed from the file, you would need to modify various entries where it is mentioned to "see under न्यायः" appropriately.

**Comment by funderburkjim** [comment]
Good suggestions.  Probably will go with nyAya.txt approach.

**Comment by Andhrabharati** [comment]
And it justifies "see below" mentioned in the meaning no. 8!

**Comment by funderburkjim** [comment]
![image](https://user-images.githubusercontent.com/6393033/120119545-44cc5980-c166-11eb-9707-413344cff0d6.png)

**Comment by funderburkjim** [comment]
Change now made.

![image](https://user-images.githubusercontent.com/6393033/120119671-f3709a00-c166-11eb-8a53-0156c79789cd.png)

**Comment by gasyoun** [comment]
> Change now made.

Best solution.
