### ISSUE TITLE
Devanagari Font ligature problem: zWy

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#22]
This pulls into a separate issue [this comment](https://github.com/sanskrit-lexicon/AP90/issues/16#issuecomment-850197998).

The Siddhanta web font is being used for Devanagari in the Cologne displays.
We chose this font several years ago in large part because it has good ligatures.
However, the comment above points out a difficulty with the display of ligature 'zWy' (SLP1):
For example 'jyEzWyaM' headword, where the 'y' looks like a 'p':

![image](https://user-images.githubusercontent.com/6393033/120224968-6551ed80-c212-11eb-9646-232f060f2643.png)

Here is what this ligature looks like (jyezWya) in Windows 10 Nirmala font in
Edge browser (This is default Devanagari font for this environment):

![image](https://user-images.githubusercontent.com/6393033/120225432-4011af00-c213-11eb-9c90-7b32cb40db8d.png)

**Comment by funderburkjim** [comment]
@Andhrabharati  (in the comment referenced above) suggests:
```
Annapurna SIL font (a free one!) seems to have both such characters and the Vedic accents well-rendered.

Probably this Annapurna SIL font could be used at the Cologne site for Devanagari characters, 
along with the Charis SIL font for the Roman characters.
```

**Comment by Andhrabharati** [comment]
Adishila font is also very good in all aspects; it is my personal choice.

**Comment by gasyoun** [comment]
> Adishila

It's nice, we can give it a try. Seems that althouth Siddhanta remains the font with most ligatures, it has at least this minor flaw.

**Comment by funderburkjim** [comment]
Which of the downloads at https://adishila.com/fonts/ should we try first?

**Comment by Andhrabharati** [comment]
The first one.

**Comment by Andhrabharati** [comment]
Just wanted to say that Annapurna SIL font looks quite similar to Siddhanta font.

So the user practically would be unaware that the font has been changed, if this is chosen.

**Comment by Andhrabharati** [comment]
isn't this issue be closed now, with Siddhanta1 font globally replacing the Siddhanta?

**Comment by funderburkjim** [comment]
Yes, can close.  Here's the current display of zWy that started this issue; it is using siddhanta1 font.

![image](https://user-images.githubusercontent.com/6393033/130717423-2c365741-d0ef-46b7-97c8-a3d39ecf1462.png)
