### ISSUE TITLE
Additional literary sources from ap90ab_v2

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#24]
A comparison was made between the literary source markup of ap90ab-v2  and that of Cologne digitization ap90.txt

**Comment by funderburkjim** [comment]
The changes may be seen in the above commit of csl-orig.

The comparisons used ap90ab_v2.txt and ap90_ls.AB.txt, from https://github.com/sanskrit-lexicon/AP90/tree/master/andhrabharati/

**Comment by Andhrabharati** [comment]
Nice to see my work(s) being helpful in someway or the other to the CDSL project.

**Comment by funderburkjim** [comment]
> M.P. | K. P. (M. P. is a typo)

M.P. occurs in both ap90 and ap57 just once under gOqaH.   Why do you say it should be 'K.P.' (Kāvyaprakāśa) ?

**Comment by funderburkjim** [comment]
> Smṛti. | Smṛti (A category of Dharmaśāstra texts)

You previously wrote: 

> Can this be taken as स्मृतितत्त्वम्? Both the citations at अर्जक & अविक्षत are picked up from VCP.

Which should be used as tooltip : `स्मृतितत्त्वम्` or `A category of Dharmaśāstra texts` ?

**Comment by funderburkjim** [comment]
ap90auth tooltips revised based on https://github.com/sanskrit-lexicon/AP90/files/6987034/unidentified.entries.with.ap57_90_unknown.tag.txt.  See commit above.

**Comment by Andhrabharati** [comment]
> > M.P. | K. P. (M. P. is a typo)
> 
> M.P. occurs in both ap90 and ap57 just once under gOqaH. Why do you say it should be 'K.P.' (Kāvyaprakāśa) ?


very simple! just read the entry text carefully, which compared the occurances in S.D. and K.P.; the opening english sentence is correctly showing both these works but the following citation has the error.

and we indeed have the corrected versions in AP PSE1912/24/65 and also AP SSE and AP S2H!!

**Comment by Andhrabharati** [comment]
> > Smṛti. | Smṛti (A category of Dharmaśāstra texts)
> 
> You previously wrote:
> 
> > Can this be taken as स्मृतितत्त्वम्? Both the citations at अर्जक & अविक्षत are picked up from VCP.
> 
> Which should be used as tooltip : `स्मृतितत्त्वम्` or `A category of Dharmaśāstra texts` ?

pl. go for स्मृतितत्त्वम्.

**Comment by funderburkjim** [comment]
Both additional corrections made.

I think this completes what was intended with this task.

**Comment by gasyoun** [comment]
> Both additional corrections made.

Final stats?

**Comment by funderburkjim** [comment]
@gasyoun   what kind of final stats do you have in mind?
