### ISSUE TITLE
Errata in APPENDIX I. SANSKRIT PROSODY

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/AP90#25]
There are {??} cases at https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/ap90app1.html 
@Andhrabharati has an eagle eye and may have a clue how to fix the missing pieces, thanks!

1)
dhanānyar{??}yadhvaṃ dhanānyarjayadhvam ||

2)
goviṃdapadābje rājī nakha{??}ṇā-
māstāṃ mama citte dhvāṃtaṃ śamayaṃtī ||

3)
vrajakāminīka{??}linīkṛtakeliḥ |

4)
kṣitivalaye'sti kaṃsaśamanastave{??} tamavocadadritanayā ||

5)
ed by a ragaṇa (-{??}-) and a short and a long vowel,
({??}-). 

[_APTE90.APPENDIX I.SANSKRIT PROSODY_IAST.docx](https://github.com/sanskrit-lexicon/AP90/files/9018058/_APTE90.APPENDIX.I.SANSKRIT.PROSODY_IAST.docx)

**Comment by drdhaval2785** [comment]
I saw the file ap90.txt in csl-orig repository. The changes have been installed.

**Comment by Andhrabharati** [comment]
@drdhaval2785 

@gasyoun was talking about the html file (referred at the top of the issue), not the ap90.txt file.
