### ISSUE TITLE
Abbreviation Markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#4]
Apte 1890 edition has two front matter sections that list 
* [abbreviations of works](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/ap90pref.html#abbreviations-of-works)
* [grammatical abbreviations](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/ap90pref.html#abbreviations-of-grammatical-terms)

It might be a good enhancement of the Cologne digitization ap90.txt to add markup for these.

Do others think time should be devoted to this?

**Comment by gasyoun** [comment]
> Do others think time should be devoted to this?

Yes. 1890 is not what people usually use, but at least out of copyright. I looked at the files and they look clean.

**Comment by drdhaval2785** [comment]
I agree. Apte 1890 is the only Apte version available online.

**Comment by funderburkjim** [comment]
Abbreviation markup added for both:
* general abbreviations  (the `<ab>` element)
* literary source abbreviations (the `<ls>` element).

The work is detailed in [markup/abls](https://github.com/sanskrit-lexicon/AP90/tree/master/markup/abls).

**Comment by funderburkjim** [comment]
## changes to repositories
Changes were made to the digitization of ap90, and also to repositories involved in the
displays.

* csl-orig repository: [ap90.txt](https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/ap90/ap90.txt)
* csl-pywork repository:
  * general abbreviation input file: [ap90ab_input.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/ap90/pywork/ap90ab/ap90ab_input.txt)
  * literary source input file [ap90auth/tooltip.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/ap90/pywork/ap90auth/tooltip.txt)
  * [inventory.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/inventory.txt) 
  * [redo_postxml.sh](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/makotemplates/pywork/redo_postxml.sh) integrate the tooltip sqlite run-time files
  * [make_xml.py](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/makotemplates/pywork/make_xml.py)  This not strictly related to abls markup.  I pushed the `<div>` markup into the ap90.xml;  formerly this markup had been added (by basicadjust.php) as part of the html generation.
* csl-websanlexicon repository. [basicadjust.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc/basicadjust.php) changed to handle the literary source abbreviations for ap90.  In addition to the tooltips for all ls markup, there are specific links for
   * Rv (Rg veda):  Example [aMsya](https://sanskrit-lexicon.uni-koeln.de/simple/ap90/aMsya/slp1)
   * Av (Atharva Veda):  There are no instances of specific references to Av in ap90.
   * P.  (Panini): Example [aMsala](https://sanskrit-lexicon.uni-koeln.de/simple/ap90/aMsala/slp1)
* csl-apidev  basicadjust.php :  this must be kept the same as the version in csl-websanlexicon so that simple-search also works.

**Comment by funderburkjim** [comment]
## Further work - general abbreviations

I added a handful of general abbreviations not so identified by [Apte preface](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/ap90pref.html#abbreviations-of-grammatical-terms).  Such as 'A.D.'  
There are no doubt others which will be noticed over time.

## Further work - literary source abbreviations

As with mw, pw, pwg,  there are numerous incompletely marked literary sources.
For example, under [guru](https://sanskrit-lexicon.uni-koeln.de/simple/ap90/guru/slp1))

![image](https://user-images.githubusercontent.com/6393033/115762253-45a4eb00-a371-11eb-87e2-5bee4c98a4f0.png)

**Comment by funderburkjim** [comment]
The two items mentioned in 'further work' should be relegated to separate issues.
I think it is ok to close this issue now.

**Comment by gasyoun** [comment]
> incompletely marked literary sources

These are `R.` related, what do you mean by incompletely? I was wondering where was Jim lost for the last days. He was with Apte.

**Comment by funderburkjim** [comment]
> incompletely?

I mean that these will require additional markup.  The current markup of the guru example is
`<ls>R. 1. 34</ls>; 3. 35; 12. 102;`  The '3. 35' and '12. 102' do not have markup.


The 'R.' literary source in AP90 means Raghuvaṃśa.  
Note the line for this source from [auth_2.txt](https://github.com/sanskrit-lexicon/AP90/blob/master/markup/abls/auth_2.txt):
```
R.:ls:115:Raghuvaṃśa (Bombay).:5297:503,517,4264,13:3
```
According to this, there are 
* 5297 instances of current 'ls' markup for 'R.' in ap90
* 503 of these are currently of form `<ls>R.</ls>`  (no numbers)
* 517 of these have one number `<ls>R. X</ls>`
   * possibly there is a problem with these; but more likely these intentionally have
      only a 'chapter', but not a verse. 
* 4264 of these have two numbers `<ls>R. X. Y</ls>`
* 13 of these have three numbers  `<ls>R. X. Y. Z</ls>`.
   * Probably there is something wrong with these. 

Thus, the typical instance has 2 numbers (chapter/verse probably).

Our two unmarked examples are unmarked because the printed text does not repeat the 'R.'.

The two examples are probably equivalent to `<ls>R. 3. 35</ls>; <ls>R. 12. 102</ls>;`

But probably we should NOT use this markup,  since this would add two 'R.' to the text.

So, we have to invent some other markup that
* does not have 'R.' displayed
* has enough information to permit tooltips for these examples
* has enough information to permit links (not currently relevant for Raghuvamśa, but is relevant for similar situations for AV, RV, Panini in this and other dictionaries)

So these unmarked items (in AP90 as well as in PWG, MW) present two difficulties:
* deciding ahead of time on the best markup for these non-standard cases
* actually identifying the non-standard cases and generating the markup.
   * There are too many cases to handle manually.  But a program to do the non-standard markup is not currently available, or theoretically clear.

**Comment by gasyoun** [comment]
> possibly there is a problem with these; but more likely these intentionally have
only a 'chapter', but not a verse.

That's what I believe in.

> Probably there is something wrong with these.

Agree, too few. @Andhrabharati your eagle-eyes wanted.

> The two examples are probably equivalent to <ls>R. 3. 35</ls>; <ls>R. 12. 102</ls>;

This is what I think it is.

> But probably we should NOT use this markup, since this would add two 'R.' to the text.

Why should it? The regex can rely on the date in the tags, not visible to the human eye, still added there.

> So, we have to invent some other markup that

Exactly and guess we are fit for that now better than ever before.

> best markup for these non-standard cases

I mean there are literally millions of such cases. Whatever you decide is best.

> But a program to do the non-standard markup is not currently available, or theoretically clear.

Let's start with just these 2 cases. Let's not try to invent something too universal now. Let's see where it gets us.

**Comment by Andhrabharati** [comment]
> I agree. Apte 1890 is the only Apte version available online.

@drdhaval2785, Apte1957 is available online at DSAL since ages!

**Comment by Andhrabharati** [comment]
> 
>     Probably there is something wrong with these.
> 
> Agree, too few. @Andhrabharati your eagle-eyes wanted.

Here are the relevant entries
```
R. x. y. z
(under L-24473) R. 1. 3. 4. 88;  should be R. 1. 3, 4. 88;

R. x. yy. z
(under L-72) R. 4. 61. 2. mist or fog. should be R. 4. 61. {2.} mist or fog. [2nd meaning]
(under L-758) R. 8. 56. 2. always should be R. 8. 56. {2.} always [2nd meaning]
(under L-17236) R. 8. 65. 3. 62. should be R. 8. 65, 3. 62.
(under L-17662) R. 8. 38. 9. 61, 11. 76. should be R. 8. 38, 9. 61, 11. 76.
(under L-26539) R. 2. 21. 6. 32, should be R. 2. 21, 6. 32,
(under L-26789) R. 6. 56. 12. 100, should be R. 6. 56, 12. 100,
(under L-30039) R. 1. 19. 4. 36, 62. should be R. 1. 19, 4. 36, 62. [Here 62 also belongs to R. 4.]
(under L-31558) R. 1. 62. 82; should be R. 1. 62, 82; [Here 82 also belongs to R. 1.]

R. xx. y. z
(under L-7099) R. 12. 5. 14. 58. 15.<>45; should be R. 12.5, 14.58, 15.<>45;
(under L-27860) R. 15. 4. 12.<>70; should be R. 15.4, 12.<>70;

R. xx. yy. z
(under L-224) R. 14. 73. 2. a <lbinfo n="Brāh+maṇa"/> should be R. 14. 73. {2.} a <lbinfo n="Brāh+maṇa"/> [2nd meaning]
(under L-24009) R. 13. 56. 15.<>82; should be R. 13. 56, 15.<>82;
```

**Comment by Andhrabharati** [comment]
> 517 of these have one number <ls>R. X</ls>
> 
>     possibly there is a problem with these; but more likely these intentionally have
>     only a 'chapter', but not a verse.

About 180 of these are R. xx.<> type [spanned to next line) and about 300 are of R. x.<> type [spanned].

**Comment by Andhrabharati** [comment]
> So these unmarked items (in AP90 as well as in PWG, MW) present two difficulties:
> 
>     deciding ahead of time on the best markup for these non-standard cases

**These are definitely not non-standard cases, but just a variant form of space saving technique.**

This is of two types-
(i) If the same work and section are referred again, they are not repeated again.
(ii) If the same work is referred again, it is not repeated.
This could either be in a continuous matter, or separated by some text in between.

Though this is mostly followed in the same entry, I have seen some such cases in the following entry as well.

**Comment by Andhrabharati** [comment]
`But a program to do the non-standard markup is not currently available, or theoretically clear.`

It's simple; one could think of using the `<inh>` tag, that was used in MW99 for genders!

**Comment by funderburkjim** [comment]
> Apte1957 is available online at DSAL since ages!

@Andhrabharati .  Yes, we all know this.  The point is that DSAL had special permission with publishers
of AP57 to permit usage.   Cologne does NOT have such permission.  Many years ago when 
Thomas made his digitization of AP57 available on the internet, there was some kind of legal objection by
the AP57 publishers.  I don't know the details, but the end result is that Cologne versions cannot be made
public.  That is why we don't have general public access to Cologne's AP57.  Copyright provisions do 
eventually 'time out'  (I think it may be 75 years) so sometime Cologne's AP57 will be available. (1957 + 75 years = 2032, so maybe then?).  Only RESEARCH usage of AP57 until then.

**Comment by drdhaval2785** [comment]
In Indian copyright act, it is after 60 years of death of the author that it comes in open domain.

V S Apte died in 1892. Therefore, the work should already be out of copyright. 
I do not understand the implication of minor editing here and there in 1957 edition. Would it bring the out of copyright work back in copyright ? In that case every publisher would publish a revised edition with 5-10 sentences changed in the text and renew his copyright.

**Comment by gasyoun** [comment]
> I have seen some such cases in the following entry as well

Oh, that hurts.

> I do not understand the implication of minor editing here and there in 1957 edition.

Is it really so minor?

> Thomas made his digitization of AP57 available on the internet, there was some kind of legal objection by
the AP57 publishers

Strange indeed. Because there are few DSAL copies around.
