### ISSUE TITLE
Hyphenated non-Devanagari 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#7]
Cologne digitization of ap90 is very close to the printed text *line by line*.
In particular, the numerous hyphenated words appear in ap90.txt with hyphenation present.
For example, within the first entry ('a'):
```
<>N. of Śiva, Brahmā, Vāyu, or Vaiśvā-    <<<<A
<>nara. {%--ind.%} {@1@} A prefix corresponding   <<B
<>to Latin {%in,%} Eng. {%in%} or {%un,%} Gr. {%a%} or
<>{%an,%} and joined to nouns, adjectives,
<>indeclinables (or even to verbs) as
<>a substitute for the negative parti-    <<<<A
<>cle {#naY,#} and changed to {#an#} before  <<B
<>vowels except in the word {#a-fRin#}.
<>The senses of {#na#} usually enumerat-  <<<<A
<>ed are six- ({%a%}) {#sAdfSya#} ‘likeness’ or   <<B
```
I propose to change ap90.txt to:
```
<>N. of Śiva, Brahmā, Vāyu, or
<>Vaiśvānara. {%--ind.%} {@1@} A prefix corresponding  <<<C
<>to Latin {%in,%} Eng. {%in%} or {%un,%} Gr. {%a%} or
<>{%an,%} and joined to nouns, adjectives,
<>indeclinables (or even to verbs) as
<>a substitute for the negative
<>particle {#naY,#} and changed to {#an#} before  <<<C
<>vowels except in the word {#a-fRin#}.
<>The senses of {#na#} usually
<>enumerated are six- ({%a%}) {#sAdfSya#} ‘likeness’ or  <<<C
```

About 26000 lines (10% of the lines in ap90.txt) end in '-' and would be changed.

**Comment by funderburkjim** [comment]
This hyphenation-removal is already done by basicadjust.php in the current displays:

![image](https://user-images.githubusercontent.com/6393033/114607355-72b71680-9c6a-11eb-8e5b-97dce56ebc15.png

So such displays would look the same after the change.

But the change would have a benefit for other analytical usage of ap90.txt.  For instance,
in the advanced search, the word 'enumerated'  (of the last line of above example) is not found within the entry for 'a'.

![image](https://user-images.githubusercontent.com/6393033/114608063-43ed7000-9c6b-11eb-8b3a-485fd32d2097.png)

If the changes are made as proposed, then 'enumerated' would be found.

**Comment by gasyoun** [comment]
> But the change would have a benefit for other analytical usage of ap90.txt

Agree. Can we have `<>Vaiśvā[]nara. {%--ind.%}` some code in the place of line break or too tough for any software?

**Comment by funderburkjim** [comment]
## One possible objection

It might be objected that such a change in ap90.txt would should not be done because 
after it is done the original hyphenated text is lost.  

However, I think this objection has little weight for this particular change, since the 
original hyphenation was done to accomodate limitations of the printing process.

**Comment by funderburkjim** [comment]
I have seen, in Wikipedia (for Whitney grammar) coding related to hyphenation.

One such way that we could preserve the original hyphenation would be as follows:
```
<>N. of Śiva, Brahmā, Vāyu, or
<>Vaiśvānara. {%--ind.%} {@1@} A prefix corresponding  <lbinfo n="Vaiśvā-nara."/>
```

**Comment by funderburkjim** [comment]
What do @Andhrabharati  and @drdhaval2785 think?

**Comment by Andhrabharati** [comment]
I am not any keen on preserving line breaks, hyphens and page breaks etc.

I would just like to see the text as a continuous free flowing paragraphs.

**Comment by gasyoun** [comment]
> Wikipedia (for Whitney grammar) coding related to hyphenation.

Love the Wikipedia approach.

**Comment by funderburkjim** [comment]
Reasons for loving the Wikipedia approach?

**Comment by gasyoun** [comment]
> Wikipedia approach
Nothing is lost. Can be reproduced, if very needed.

**Comment by drdhaval2785** [comment]
I lean towards keeping the hyphenations as they are in ap90.txt. 
Otherwise, at least would love to see some marker to show that there earlier was a hyphen there.

**Comment by Andhrabharati** [comment]
I may bring to the team's notice that MW99 has been done without hyphenations (mostly, if not throughout).

So, what would Marcis (to bring back if needed) and Dhaval (to show that there was a hyphen) say on this?

(My one and only principle is to have uniformity and consistency in (and across) the works.)

**Comment by drdhaval2785** [comment]
If line breaks are not digitized, we have no way to bring them to life except manually. If line breaks are digitized, situation is different

**Comment by gasyoun** [comment]
> Otherwise, at least would love to see some marker to show that there earlier was a hyphen there.

That is what Wikipedia markup has - in the code, `to show that there earlier was a hyphen there`

> (My one and only principle is to have uniformity and consistency in (and across) the works.)

Impossible, but wanted at Cologne right now.

**Comment by funderburkjim** [comment]
In a strict sense, consistency across dictionaries digitized by Cologne is not possible.   We start with the digitizations as they were made by Thomas over a long period of time.  Consistency would require determination of  a  complete 'theory of digitization' before beginning the first digitization; and then adherence to that theory throughout the digitization process.  

Our current approach does attempt to impose consistency across dictionaries to some considerable degree:
* in the base form of the digitizations (as in csl-orig),  there is consistency in
  * using UTF-8 encoding
  * identifying headword entries by the 'metaline'
  * representing Devanagari text in slp1 transcoding
  * using modern IAST conventions in place of dictionary specific diacritics
* in the xml form of the digitization, there is further consistency
  * requirement that the xml file indeed be well-formed xml, which further conforms to a particular xml Document-type-definition which is the same for all dictionaries
  * Some differences among dictionaries in the csl-orig metaline stage are removed in the xml form. For example  `{#X#}` in apte.txt is replaced by `<s>X</s>` (devanagari text) in apte.xml, while in MW, mw.txt already has `<s>X</s>`.   
* Still more consistency is present in the html forms of the displays.  For a recent example, GRA dictionary `{a,b}` markup appears in both gra.txt and gra.xml; but `<ls>RV. x,y,z</ls>` appears in mw.txt and mw.xml;  but both of these become quite similar in the html of displays.

It would have been wonderful if our digitizations could have been coded originally within the context of a robust theoretical position.   But alas, life did not work this way.

**Comment by funderburkjim** [comment]
Regarding hyphenation -
 Although I am inclined to agree with @Andhrabharati's position on this,  I am also reluctant to do an information-losing change to a digitization when there is, as in this case, a way to make the change in a nearly lossless way by adding markup.

Since @gasyoun and @drdhaval2785 have a definite opinion in this case, and I can see their point and think I can implement the idea,  I will go with that.

Namely, as in the example above, in addition to resolving the hyphenated words, I'll add the markup as in the example `<lbinfo n="Vaiśvā-nara."/>`

Will provide more details as process continues.

Thanks to all for your thoughtful feedback :)

**Comment by gasyoun** [comment]
> Namely, as in the example above, in addition to resolving the hyphenated words, I'll add the markup as in the example <lbinfo n="Vaiśvā-nara."/>

Sounds like a plan.

> wonderful if our digitizations could have been coded originally within the context of a robust theoretical position. But alas, life did not work this way.

So we can write now how it should be done at that time ))

**Comment by funderburkjim** [comment]
New version ap90 now installed.

One variance:
```
OLD
<>N. of Śiva, Brahmā, Vāyu, or Vaiśvā-    <<<<A
<>nara. {%--ind.%} {@1@} A prefix corresponding   <<B
NEW
<>N. of Śiva, Brahmā, Vāyu, or <lbinfo n="Vaiśvā+nara"/>
<>Vaiśvānara. {%--ind.%} {@1@} A prefix corresponding
```
Note 1:  the `<lbinfo` was put on line ending in '-'
Note 2: The lbinfo attribute value has the two parts separated by a '+', rather than '-'.
 This is because there are a few cases where one of the 'parts' also has a '-'.  For example:
```
OLD:
<>action. 2. renunciation of self-right-
<>eousness. {#--SIla#} {%a.%} lazy, indolent.
NEW:
<>action. 2. renunciation of <lbinfo n="self-right+eousness"/>
<>self-righteousness. {#--SIla#} {%a.%} lazy, indolent.
```
By using the '+', we can know that the line-break originally occurred after 'self-right'.

A 'restore hyphen' program was also written.  When applied to the version with `<lbinfo`,
we can get the original form.  

We now have the improvement in advanced search, anticipated in comment above:

![image](https://user-images.githubusercontent.com/6393033/114779936-b41bf480-9d44-11eb-8f23-4e1c0fd597fc.png)

**Comment by funderburkjim** [comment]
## Technical notes
The code and change files are put in [hyphen/hyphen_eng](https://github.com/sanskrit-lexicon/AP90/tree/master/hyphen/hyphen_eng) in this repository.

The readme file enumerates the steps taken.

Note the 'Suggestions for further improvement' at the bottom of the readme file of above directory.


## spellchecker module

I installed a spellchecker module ('pip install spellchecker') to validate words constructed after hyphenation.   This is different than the PyEnchant checker I've used before, and seems
preferable because of the easy  pip-install availability.  Not sure how it's quality compares with that of Pyenchant, but first impressions are positive.
The code is also at Github: https://github.com/barrust/pyspellchecker

**Comment by funderburkjim** [comment]
This completes goals of this issue.

Anticipate doing a similar task for devanagari words with hyphen at end of lines.

**Comment by gasyoun** [comment]
> By using the '+', we can know that the line-break originally occurred after 'self-right'.

Understood.

> A 'restore hyphen' program was also written. When applied to the version with <lbinfo,
we can get the original form.

`python restore_hyphen_eng.py ap90_1.txt hyphen_restore_changes.txt` great, everything you have thought about.

> 'type=false' in hyphen_changes.txt  After resolution of hyphens, the resulting word was checked against  an English spell check dictionary.  About 3000 of the 26000 cases  were NOT confirmed.  These could be checked.

Guess we can ask @sanskritisampada one day, thanks.
