### ISSUE TITLE
Hyphenated Devanagari at line end

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#8]
Changes made to digitization of ap90 similar to that of #7, but for Devanagari.

For example, under headword aMhu:

![image](https://user-images.githubusercontent.com/6393033/115154566-863af680-a049-11eb-9c3e-954fa88631ae.png)

The change in digitization of ap90.txt:
```
OLD:
<>wicked, injurious ({#pApakArin, ha-#}
<>{#nanaSIla;#}) strait, narrow (?) {#--hu#} {%n.%}
NEW:
<>wicked, injurious ({#pApakArin, #} <lbinfo n="ha#nanaSIla"/>
<>{#hananaSIla;#}) strait, narrow (?) {#--hu#} {%n.%}
```

**Comment by funderburkjim** [comment]
## Technical notes
The code and change files are put in [hyphen/hyphen_deva](https://github.com/sanskrit-lexicon/AP90/tree/master/hyphen/hyphen_deva) in this repository.

The readme file enumerates the steps taken.

**Comment by gasyoun** [comment]
> <lbinfo n="ha#nanaSIla"/>

All data remains, perfect.
