### ISSUE TITLE
Abbrev markup: compar. and superl.

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/AP90#9]
These two abbreviations were not mentioned among Apte's list of general abbreviations.
Each occurs 55 times, as either 'compar.' or 'Compar.' and 'superl.' or 'Superl.'

It seems appropriate to handle these as *general* abbreviations: `<ab>superl.</ab>` etc.

**Comment by gasyoun** [comment]
> It seems appropriate to handle these as general abbreviations: <ab>superl.</ab> etc.

Agree.

**Comment by funderburkjim** [comment]
These now handled.  See #11.
